server:
  port: 8080  # Gateway service runs on this port

spring:
  application:
    name: gateway-service  # Unique service name for Eureka registration
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081  # Load-balanced URI for the User Service
          predicates:
            - Path=/api/users/**      # Routes requests starting with /users
        - id: product-service
          uri: http://localhost:8082  # Load-balanced URI for the Product Service
          predicates:
            - Path=/api/products/**   # Routes requests starting with /products
        - id: order-service
          uri: http://localhost:8083  # Load-balanced URI for the Order Service
          predicates:
            - Path=/api/orders/**     # Routes requests starting with /orders

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10  # Heartbeat interval
    lease-expiration-duration-in-seconds: 30  # Lease expiry