spring:
  application:
   name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/product-service
    username: postgres
    password: Singama@98
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 10  # Heartbeat interval
    lease-expiration-duration-in-seconds: 30  # Lease expiry